### ISSUE TITLE
RPC doesn't update

### ISSUE THREAD

**Issue by thecoder876** [replit-discord/replit-desktop#152]
**Describe the bug**
The RPC doesn't update when you open a repl. I've tried both the alpha and stable versions, but neither of them seem to work.

**To Reproduce**

1. Open the app and Discord
2. Open a repl
3. See the error in Discord status

**Expected behavior**
The RPC should have displayed the repl name and langauge.

**Screenshots**
![Screenshot 1](https://user-images.githubusercontent.com/76265544/109003823-cdd38080-769f-11eb-9388-c46e389674c8.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: Alpha 3 and Stable 2

**Repl**
The web version doesn't connect to Discord.

**Additional context**
The RPC actually shows `repl.it/` as the file name.

**Comment by frissyn** [comment]
@leon332157 @spotandjake Could y'all stop messing with my hard work? I got it working just fine in my `frissyn-rpc` branch and you guys goofed it. Imma fix it this weekend using VSC file detection **first**, Repl language detection **second**, and after that, y'all are on your own. >:(

**Comment by spotandjake** [comment]
It is working just fine I tested it yesterday for a few hours I get the feeling it just isn't working in alpha but should be working in dev

**Comment by whippingdot** [comment]
Hey the dev branch doesn't work at all...Just get an error

**Comment by CoolCoderSJ** [comment]
> 
> 
> Hey the dev branch doesn't work at all...Just get an error

@whippingdot If it doesn't work for you please create a new issue unless it is related to the Discord RPC.

**Comment by whippingdot** [comment]
Cause of tis but k
![image](https://user-images.githubusercontent.com/64354499/109009042-0d1bc480-76d4-11eb-9748-d668dd4663bd.png)

**Comment by leon332157** [comment]
@whippingdot It doesn't work because you don't have discord installed most likely. RPC requires the discord desktop client.

**Comment by spotandjake** [comment]
May you test my dev branch as well as most issues related to rpc should be fixed.

**Comment by thecoder876** [comment]
> May you test my dev branch as well as most issues related to rpc should be fixed. #147

@spotandjake ok

**Comment by spotandjake** [comment]
May you let me know if using my branch Fixed the issue.
