### ISSUE TITLE
New option: Reset settings

### ISSUE THREAD

**Issue by cursorweb** [replit-discord/replit-desktop#163]
Currently clearing all cookies only work for replit-made cookies. Not any preference we have made using the app.

It would be nice just to reset all the options in case you make a mistake.

**Comment by spotandjake** [comment]
Eh don't think it is needed just yet, maybe v4 if we add more stm you can just get defaults within like 3 btns it so

**Comment by cursorweb** [comment]
still, when it gets more extensible, this will be very useful

**Comment by cursorweb** [comment]
Resolved from #165
