### ISSUE TITLE
GitHub Oauth is broken while on mobile view

### ISSUE THREAD

**Issue by leon332157** [replit-discord/replit-desktop#164]
The OAuth doesn't seem to trigger window.opener.postMessage thus breaking the OAuth workflow.

**Comment by spotandjake** [comment]
Can look into Monday

**Comment by spotandjake** [comment]
Think i fixed this just got to create a pr.

**Comment by leon332157** [comment]
Now also broken on desktop.

**Comment by leon332157** [comment]
Update: fixed after resetting userData
