### ISSUE TITLE
Add better titles for Discord RPC

### ISSUE THREAD

**Issue by EliteHaxy** [replit-discord/replit-desktop#172]
It would be cool if it was kinda like the VS code extension. It would say repl.it, then editing (file) then (the file type) and etc. Right now my RPC just says repl.it/login.

Thanks!

**Comment by EliteHaxy** [comment]
Edit: This may be a bug as I see other screenshots where it works like this. Is it because I'm on 3.0.0?

**Comment by leon332157** [comment]
Are you using the alpha?

**Comment by EliteHaxy** [comment]
> Are you using the alpha?

Yes I am. And I tried downloading 2.1.0 but whenever I logged in with google, it said this device is unauthorized.

**Comment by leon332157** [comment]
The RPC in alpha1 is broken, I'll probably release another version today with more bug fixes. You can use the development version before I release a new alpha.

**Comment by EliteHaxy** [comment]
> The RPC in alpha1 is broken, I'll probably release another version today with more bug fixes. You can use the development version before I release a new alpha.

Ok where is the development version? As in 2.1.0 I can't log in with google. Also how can I disable notifications?

**Comment by leon332157** [comment]
You can clone the GitHub repo and run it with instructions in the README

**Comment by EliteHaxy** [comment]
Ok ill see

**Comment by leon332157** [comment]
try out the new version i just released.

**Comment by EliteHaxy** [comment]
Ok

**Comment by EliteHaxy** [comment]
Nope everytime I login with google it syas redirecting forever

**Comment by leon332157** [comment]
Can you send a screenshot

**Comment by leon332157** [comment]
Update: I have identified the issues and is implementing a fix. @EliteHaxy In the mean time, you should go to the login window, click in the menu Window > Go To Home

**Comment by EliteHaxy** [comment]
> Update: I have identified the issues and is implementing a fix. @EliteHaxy In the mean time, you should go to the login window, click in the menu Window > Go To Home

Ok ty

**Comment by EliteHaxy** [comment]
Also would you like me to be a tester for it?

**Comment by leon332157** [comment]
Sure, I think we need for testers, to if you find someone else whos also interested, make sure you tell them about it.

**Comment by EliteHaxy** [comment]
Sure. I found an issue not sure, but it doesn't say the file name it just shows the url 
![image](https://user-images.githubusercontent.com/67123306/110662434-1fddd100-818b-11eb-8dd3-6b28f752b05d.png)

**Comment by EliteHaxy** [comment]
It also has random lag spikes

**Comment by leon332157** [comment]
Where are you pasting into?

**Comment by leon332157** [comment]
Fixed.

**Comment by leon332157** [comment]
@EliteHaxy try using alpha6, a lot of issues has been fixed.

**Comment by sorenrood** [comment]
Going to try this out sometime today. 👍🏻

**Comment by EliteHaxy** [comment]
> @EliteHaxy try using alpha6, a lot of issues has been fixed.

Ok will do

**Comment by EliteHaxy** [comment]
In alpha 6 there is a google login issue...

**Comment by leon332157** [comment]
@EliteHaxy Fixed in the latest commit. Also, do you have the issue where every time u restart the app you need to login again?

**Comment by EliteHaxy** [comment]
Yes I do need to login every time. Is the latest release have the google login fix?

**Comment by leon332157** [comment]
@EliteHaxy I released https://github.com/replit-discord/replit-desktop/releases/tag/3.0.0-alpha.7
Can you make sure to delete ```C:\\Users\<username>\.replit``` before you test since that could be related to the logout issue.

**Comment by EliteHaxy** [comment]
Ok I will test this out right now!

**Comment by EliteHaxy** [comment]
First issue, when you open the app, all the page windows aren't centered.
 Love the new google login. 
 
Everything else is fine! RPC and everything!

**Comment by EliteHaxy** [comment]
If you leave the application open for a couple minutes it lags and says not responding. If you fix that lag issue, this will be perfect!

**Comment by EliteHaxy** [comment]
Also when you close the application, then reopen it it logs you out of google.

**Comment by leon332157** [comment]
It's designed to do it because we had issues before if oauth pages don't get logged out, but I can remove that.

**Comment by leon332157** [comment]
fixed in latest verison.

**Comment by leon332157** [comment]
@EliteHaxy Can you test the beta version, logout issue should be fixed.

**Comment by EliteHaxy** [comment]
> @EliteHaxy Can you test the beta version, logout issue should be fixed.

Sure will do!

**Comment by EliteHaxy** [comment]
Yay! I stay logged in when I exit and reopen. 

But an issue has arose...

After downloading the .exe file, it automatically opens the repl login page like its supposed to. I then pinned my repl home page. Then after I exit to test the google login, it says the shortcut has been removed or etc. So basically you need to pin the exe you download and not the window it opens (for the first time after downloading exe). Then after that you are good to go. 

(When will auto updater come???) c:

![image](https://user-images.githubusercontent.com/67123306/111015546-e1a10700-836e-11eb-996f-8f11389b8491.png)

**Comment by leon332157** [comment]
The auto updater will come when it's stable. And I'm aware there's a lot of issues with portable build, so I'm just going to remove it. But at the same time, I'll also add a auto-update into testing versions, so it saves you some time.

**Comment by EliteHaxy** [comment]
Sure

**Comment by EliteHaxy** [comment]
Any updates?

**Comment by leon332157** [comment]
Nothing much, I'm working on another project which should replace this one. https://github.com/leon332157/replish

**Comment by whippingdot** [comment]
I don't understand that project ~~can you give a more clear description for bots and noobs like me~~

**Comment by leon332157** [comment]
It's should allow you to edit code on replit with VSCode and without the need for crosis. So instead of syncing the code, I can turn a repl into a virtual machine to code.

**Comment by whippingdot** [comment]
ok i kinda understood that. The only thing is - doesn't replit already have there own extension to run repls on vs code? I know it is for mods only unless you ask for permission, but still...

**Comment by spotandjake** [comment]
this is a lot different the other one runs on crosis which you had to get a key to use. not to mention crosis has been discontinued  with no immideaate plans on being continued in the future. i am also closing this issue as it has gotten off topic and the initial issue looks to have been fixed.
