### ISSUE TITLE
Incorrect Installation Instructions in readme.md

### ISSUE THREAD

**Issue by sorenrood** [replit-discord/replit-desktop#173]
### The git link in the `Dev Installation & Usage` section does not work. This is (probably) because the organization name was changed from `repl-it-discord` to `replit-discord`.

![image](https://user-images.githubusercontent.com/49735495/110688423-6a187f80-8196-11eb-9ffd-b18521313b0b.png)

**This is the error when you copy-paste what's currently in step 1:**

![image](https://user-images.githubusercontent.com/49735495/110688610-9b914b00-8196-11eb-93e5-4f7c376effb7.png)

**To fix, change to this:**
```
1. Clone the repository
git clone git@github.com:replit-discord/replit-desktop.git
cd replit-desktop
```

**Notice the change from `git@github.com:repl-it-discord...` to `git@github.com:replit-discord...`**

**Comment by sorenrood** [comment]
I tried to fix it myself, but I don't have the perms to make branches or make PRs.

**Comment by spotandjake** [comment]
thanks will fix

**Comment by leon332157** [comment]
Fixed.

**Comment by sorenrood** [comment]
:fire:
