### ISSUE TITLE
Env icon is hidden.

### ISSUE THREAD

**Issue by zplusfour** [replit-discord/replit-desktop#174]
when you go to the buttons bar, you'll see that the environment variables icon is hidden, but it works on replit.com (browser not desktop)

**Screenshots**
![image](https://user-images.githubusercontent.com/73612690/110974437-32146680-8367-11eb-8c1b-3c5adc1c1333.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 88

**Comment by spotandjake** [comment]
I am not seeing this issue on my copy can you check if there is anything in dev tools console

**Comment by ch1ck3n-byte** [comment]
i see it.

**Comment by leon332157** [comment]
Closed as inactivity
