### ISSUE TITLE
999

### ISSUE THREAD

**Issue by tylerveen** [replit-discord/replit-desktop#175]
Describe the bug
A clear and concise description of what the bug `is.`

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Repl**
Does this bug also appear on the web version on Replit?

**Additional context**
Add any other context about the problem here, like the long-term effects of the problem.

**Comment by leon332157** [comment]
Closed as spam
