### ISSUE TITLE
Replit-desktop-bug

### ISSUE THREAD

**Issue by AestraDev** [replit-discord/replit-desktop#186]
**Describe the bug**

Launching windows stuck bug

**To Reproduce**

1. Go to 'application'
2. Click on 'open'
3. It will stuck on launching screen

**Expected behavior**

I expected it to open faster

**Screenshots**

![image](https://user-images.githubusercontent.com/71583327/124085185-63778600-da6d-11eb-9ea1-0d6525a53205.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser : chrome
 - Version: replit version - beta

**Repl**

Does this bug also appear on the web version on Replit?

- Nope

**Additional context**

I thought it was once only but it stuck everytime whenever i start

**Comment by leon332157** [comment]
Windows 7 is not supported by electron. Also, please launch the exe with cmd to see if there's an error message in the console.

**Comment by AestraDev** [comment]
I have doubt, if it was not supported in windows 7 then why he started on first time and when I quit the application it doing this

**Comment by leon332157** [comment]
Can you use cmd to launch replit.exe and check if theres any error in the console?

**Comment by AestraDev** [comment]
I can't now but whenever I will I will post an screen shot

**Comment by AestraDev** [comment]
Hey Leon can you tell me how can I open it with cmd I am bit confused about it..

**Comment by leon332157** [comment]
open cmd, `cd` into the download directory and run "Replit Desktop.exe" or whatever the exe name is

**Comment by AestraDev** [comment]
![image](https://user-images.githubusercontent.com/71583327/124345013-b1b69180-dbf3-11eb-9e96-543f05aeb934.png)
Here it doesn't get any error in console but I want you to know one more thing that when i turn off my internet connection it work fine like it load that offline.html file and when i turn it on and click on "Go Online" or whatever it work fine means the problem is in that checking update part not only with current application but in other like visual studio code when i click on update it give's **net::err_cert_authority_invalid** problem while it works fine with another things that connect with internet like extensions I just told this because there is like some chances that replit also have same problem can you help me with it please...

**Comment by leon332157** [comment]
If you are getting certificate errors there's most likely problems with your windows or internet configuration,

**Comment by AestraDev** [comment]
Can you tell me how I can fix it

**Comment by leon332157** [comment]
If you want to join the discord server I can help you find the problem and attempt to fix it.

**Comment by AestraDev** [comment]
yeah thay will be more helpful to me can i get the link please

**Comment by leon332157** [comment]
Replit.com/discord

**Comment by AestraDev** [comment]
Oh i am already there can you give me your tag and username

**Comment by AestraDev** [comment]
Oh i got it messaging you there thanks
