### ISSUE TITLE
Portable mode?

### ISSUE THREAD

**Issue by WatermelonSalt** [replit-discord/replit-desktop#188]
**The Question:**

Hello, I don't really know if this is the correct sub-issue classification to ask this but this issue is more of a question than a feature, if you look at it like that. Getting to the point, this issue is about a `Portable` mode in Windows OS. Refer to the *Additional Context* section if you wish to know what I exactly mean by a `Portable` mode.

**The Bridge:**

I don't know if a `Portable` mode already exists for this app and I would like to know how to trigger it in case it already exists, if it does not exist already, please read along to the next section of this issue.

**Expected Solution:**

From the *About* section of this wonderful repo I understood that this app is made with `electron` and `electron` apps usually store many files in `%APPDATA%` and sometimes in `%LOCALAPPDATA%`. I don't know of any other place that an electron app or this app itself stores its files and the expected behavior in portable mode would be to contain all these files inside the **`root`** folder of the app itself.

**Alternative Solution:**

An alternative solution would be to package the app in [portableapps format](https://portableapps.com/) if not possible natively.

**Additional context:**

> "Portable", here, means that the program must store its files near itself and not all over the filesystem such as `%APPDATA%, %LOCALAPPDATA%, %PROGRAMDATA%, %USERPROFILE%, and folders inside %USERPROFILE% like Documents, etc.`

**Comment by leon332157** [comment]
There’s no code to accommodate for custom location of settings file, if that is what you are asking. Because of that, portable here only means a self-extracting exe that doesn’t require install.

**Comment by leon332157** [comment]
The reason I included a single exe release is that it makes distributing and testing easier, and since most if not all users of this app will not be switching between computers or installing the app to a flash drive, there was no need to make this app “portable”.

**Comment by WatermelonSalt** [comment]
Oh, hey! I'm glad that you read my issue and commented on it. Yeah, I was expecting that there would be a way to store the settings in a different folder next to the root. I'll find a way to "portableize" it myself. Thanks. Looking forward to future releases. Keep up the good work!
