### ISSUE TITLE
Mac M1 Build! 

### ISSUE THREAD

**Issue by codergautam** [replit-discord/replit-desktop#190]
The latest build didnt work for me with M1 Mac (same issue as #185 )

I built the project on my m1 mac (no code changes) and I am able to run the app without issues.

Here is a download link: https://drive.google.com/file/d/1mTz57gTarITmN02TV-EBSL_LzJH6qmuw/view?usp=sharing

Hope this helps

**Comment by leon332157** [comment]
Thank you, I'll upload it.
